server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: econome
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    skip-default-callbacks: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  issuer: ${JWT_ISSUER}
  access-key: ${JWT_ACCESS_KEY}
  refresh-key: ${JWT_REFRESH_KEY}
  access-token-expiration-minutes: 10
  refresh-token-expiration-days: 30