name: build-test-containerize
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
  JWT_ACCESS_KEY: ${{ secrets.JWT_ACCESS_KEY }}
  JWT_REFRESH_KEY: ${{ secrets.JWT_REFRESH_KEY }}
jobs:
  app-build-test-container-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x gradlew
      - run: ./gradlew build

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
