name: deploy
on:
  push: 
    branches:
      - prod
jobs:
  deploy:
    runs-on: econome
    steps:
      - name: Pull Image from GitHub Container Registry
        run: sudo docker pull ghcr.io/limvik/budget-management-service:main
      - name: Delete old container
        run: sudo docker rm -f econome-app
      - name: Run container
        run: sudo docker run -d --env-file .env -p 80:9001 --name econome-app ghcr.io/limvik/budget-management-service:main